version: '1'
services:
  hadoop-master:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - 50070:50070
      - 8088:8088
      - 9870:9870
      - 8080:8080
      - 8888:8888
    volumes:
      - ./data:/data

  spark-worker-1:
    image: bde2020/spark-worker
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master

  spark-master:
    image: bde2020/spark-master
    container_name: spark-master
    hostname: spark-master
    ports:
      - 7077:7077
      - 8081:8081
    environment:
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8081


  hive-server:
    image: bde2020/hive-metastore-postgresql
    container_name: hive-server
    hostname: hive-server
    ports:
      - 10000:10000
      - 9083:9083
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - hive-metastore
  
  hive-metastore:
    image: bde2020/hive-metastore-postgresql
    container_name: hive-metastore
    hostname: hive-metastore
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data/hive:/var/lib/hive

  webserver:
    image: apache/airflow:latest
    container_name: airflow
    hostname: airflow
    ports:
      - 8082:8080
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: webserver
    depends_on:
      - scheduler
      - postgres

  scheduler:
    image: apache/airflow:latest
    command: scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  
  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    hostname: jupyter
    ports:
      - 8889:8888
    volumes:
     - ./notebooks:/turtle/

volumes:
  pgdata: