version: '1'
services:
  hadoop-master:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - 50070:50070
      - 8088:8088
      - 9870:9870
      - 8080:8080
      - 8888:8888
    volumes:
      - ./data:/data

  spark-worker-1:
    image: bde2020/spark-worker
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master

  spark-master:
    image: bde2020/spark-master
    container_name: spark-master
    hostname: spark-master
    ports:
      - 7077:7077
      - 8081:8081
    environment:
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8081