version: '1'
services:
  hadoop-master:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - 50070:50070
      - 8088:8088
      - 9870:9870
      - 8080:8080
      - 8888:8888
    volumes:
      - ./data:/data
    